---
- name: Report Users NOT logged on in the last 10 days with win_powershell module
  hosts: all
  gather_facts: True
  vars:
    mysource: ''
    package_name: ''

  tasks:
    - name: Get-LocalUsers NOT logged on in 10 days
      ansible.windows.win_powershell:
        script: |
          Get-UserLastLogon
      register: userlastlogon

    - debug: msg=userlastlogon

    - name: Get-LocalUsers NOT logged on in 10 days
      ansible.windows.win_powershell:
        script: |
          Get-LocalUser | Where-Object {$_.Lastlogon -ge (Get-Date).AddDays(-10)} | Select-Object Name,Enabled,SID,Lastlogon | Format-List
      register: userlastlogon10

    - debug: msg=userlastlogon10

    - name: Find user last logon time
      ansible.windows.win_powershell:
        script: |
          Get-ADUser -Filter {Name -eq "admin"} -Properties * | Select-Object Name, @{N='LastLogon'; E={[DateTime]::FromFileTime($_.LastLogon)}}
      register: userlastlogon10

    - debug: msg=userlastlogon10